# name: Deploy Website to S3

# on:
#   push:
#     branches: [ main ]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3
#       - name: Install Terraform
#         run: |
#           curl -fsSL (link unavailable) | sudo apt-key add -
#           sudo apt-add-repository "deb [arch=amd64] (link unavailable) $(lsb_release -cs) main"
#           sudo apt-get update && sudo apt-get install terraform
#       - name: Terraform Init
#         run: terraform init
#       - name: Terraform Apply
#         run: terraform apply -auto-approve
#       - name: Upload to S3
#         run: aws s3 cp ./website s3://your-website-bucket/ --recursive
